var statsInOrder = [
	"strength",
	"dexterity",
	"constitution",
	"intelligence",
	"wisdom",
	"charisma",

	"strengthSave",
	"dexteritySave",
	"constitutionSave",
	"intelligenceSave",
	"wisdomSave",
	"charismaSave",

	"acrobatics",
	"animalHandling",
	"arcana",
	"athletics",
	"deception",
	"history",
	"insight",
	"intimidation",
	"investigation",
	"medicine",
	"nature",
	"perception",
	"performance",
	"persuasion",
	"religion",
	"sleightOfHand",
	"stealth",
	"survival",
	"initiative",

	"hitPoints",
	"armor",
	"dexterityArmor",
	"speed",
	"proficiencyBonus",
	"ki",
	"sorceryPoints",
	"rages",
	"rageDamage",
	"expertiseDice",
	"superiorityDice",
	"carryMultiplier",

	"level1SpellSlots",
	"level2SpellSlots",
	"level3SpellSlots",
	"level4SpellSlots",
	"level5SpellSlots",
	"level6SpellSlots",
	"level7SpellSlots",
	"level8SpellSlots",
	"level9SpellSlots",

	"d6HitDice",
	"d8HitDice",
	"d10HitDice",
	"d12HitDice",

	"acidMultiplier",
	"bludgeoningMultiplier",
	"coldMultiplier",
	"fireMultiplier",
	"forceMultiplier",
	"lightningMultiplier",
	"necroticMultiplier",
	"piercingMultiplier",
	"poisonMultiplier",
	"psychicMultiplier",
	"radiantMultiplier",
	"slashingMultiplier",
	"thunderMultiplier",
];

statOrder = {};
_.each(statsInOrder, function(element, index){
	statOrder[element] = index;
});