services:
  dicecloud-db:
    container_name: dicecloud-db
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - /data/dicecloud/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - '${MONGO_PORT}:27017'
    networks:
      - dicecloud

  dicecloud-app:
    container_name: dicecloud-app
    image: dicecloud-app:2.1.0-SNAPSHOT
    #build:
    # context: ./
    environment:
      # Node Performance
      - NODE_OPTIONS=${NODE_OPTIONS}
      - WEBAPP_THREAD_POOL_SIZE=${WEBAPP_THREAD_POOL_SIZE}
      
      # Node Environment
      - NODE_ENV=${NODE_ENV}
      - NODE_MODULES_CACHE=${NODE_MODULES_CACHE}
      - GZIP=${GZIP}
      
      # Meteor Settings
      - METEOR_ALLOW_SUPERUSER=${METEOR_ALLOW_SUPERUSER}
      - METEOR_DISABLE_OPTIMISTIC_CACHING=${METEOR_DISABLE_OPTIMISTIC_CACHING}
      - METEOR_NO_RELEASE_CHECK=${METEOR_NO_RELEASE_CHECK}
      - METEOR_DISABLE_OPLOG=${METEOR_DISABLE_OPLOG}
      
      # Application Settings
      - ROOT_URL=${ROOT_URL}
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@dicecloud-db
      - PORT=${PORT}
      - METEOR_SETTINGS=${METEOR_SETTINGS}
      - MAIL_URL=${MAIL_URL}
    ports:
      - '${PORT}:${PORT}' #The internal port should match the port set in the environmental variables
    depends_on:
      - dicecloud-db
    networks:
      - dicecloud

networks:
  dicecloud:
    name: dicecloud
    driver: bridge
