version: "3.7"
services:
  web:
    restart: always
    build:
      context: ./
    environment:
      - NODE_ENV="production"
      - MONGO_URL="mongodb://dice:dice@dicecloud_mongodb_1:27017"
      - ROOT_URL=http://127.0.0.1:3000
    ports:
      - "3000:3000"
      - "3003:3003"
  mongodb:
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dice
      - MONGO_INITDB_ROOT_PASSWORD=dice
    volumes:
      - ./db:/data/db
    
