import '/imports/api/simpleSchemaConfig.js';
import '/imports/server/config/SimpleRestConfig.js';
import '/imports/server/config/limitLoginTokens.js';
import '/imports/server/rest/index.js';
import '/imports/server/config/accountsEmailConfig.js';
import '/imports/server/config/simpleSchemaDebug.js';
import '/imports/server/config/SyncedCronConfig.js';
import '/imports/server/config/redisCaching.js';
import '/imports/server/publications/index.js';
import '/imports/server/cron/deleteSoftRemovedDocuments.js';
import '/imports/api/parenting/organizeMethods.js';
import '/imports/api/users/patreon/updatePatreonOnLogin.js';
import '/imports/api/engine/actions/index.js';
import '/imports/migrations/server/index.js';
import '/imports/migrations/methods/index.js'
import '/imports/constants/MAINTENANCE_MODE.js';
import '/imports/api/creature/creatureProperties/methods/index.js';
import '/imports/api/creature/archive/methods/index.js';
import '/imports/api/creature/creatures/methods/index.js';
