DAMAGE_TYPES = {
	"acid":        {name: "Acid"},
	"bludgeoning": {name: "Bludgeoning"},
	"cold":        {name: "Cold"},
	"fire":        {name: "Fire"},
	"force":       {name: "Force"},
	"lightning":   {name: "Lightning"},
	"necrotic":    {name: "Necrotic"},
	"piercing":    {name: "Piercing"},
	"poison":      {name: "Poison"},
	"psychic":     {name: "Psychic"},
	"radiant":     {name: "Radiant"},
	"slashing":    {name: "Slashing"},
	"thunder":     {name: "Thunder"},
};

DAMAGE_MULTIPLIERS = [
	"acidMultiplier",
	"bludgeoningMultiplier",
	"coldMultiplier",
	"fireMultiplier",
	"forceMultiplier",
	"lightningMultiplier",
	"necroticMultiplier",
	"piercingMultiplier",
	"poisonMultiplier",
	"psychicMultiplier",
	"radiantMultiplier",
	"slashingMultiplier",
	"thunderMultiplier",
];
